- name: play1
  hosts: web_server
  gather_facts: false
  tasks:
  - name:  update
    apt: 
      update_cache: true
      
  - name:  install
    package: 
      name: nginx
      state: latest
  
  - name:  copy
    copy: 
      src: ./index.html
      dest: /var/wwww/html/
    
  - name: restarted task
    service: 
      name: nginx
      state: restarted

  