- name: play1
  hosts: web_server
  gather_facts: false
  tasks:

  - name:  update
  tags: one
    apt: 
      update_cache: true
      
  - name:  install
  tags: two
    package: 
      name: nginx
      state: latest
  
  

  