- name: installing
  apt:
    name: "{{ package_name }}"
    state: latest
  register: installing_output 
  notify:
    - copying 
    

- name: temp
  template: 
    src: templates/index.html.j2
    dest: /var/www/html/
  
    


# - name: copying  
#   copy: 
#     src: "{{ item }}"
#     dest: /var/www/html/
#   loop: "{{ my_list }}"
#   when: commands_output.changed == true #ther should be handlers
#   register: copying_output

# - name: restarting
#   service: 
#     name: "{{ package_name }}"
#     state: restarted
#     #there should be handler
#   when: copying_output.changed == true